import id from './id';
import * as utils from './utils';
import * as utilsLink from './utils-link';
import { getQueryRevisionError } from './utils-api';

import Api from './Api';
import Article from './Article';
import Button from './Button';
import view from './view';
import settings from './settings';

import './styles/links.less';

const { h } = utils;

/**
 * Link configuration options
 * @typedef {Object} Link.Options
 * @property {'basic'|'request'|'event'|'none'} [behavior='basic'] - A Link behavior type
 * @property {'insertAfter'|'insertBefore'} [insertMethod='insertAfter'] - Define where to embed actions panel
 * @property {boolean} [showLink=false] - Whether to show the link action
 * @property {boolean} [showPageLink=true] - Whether to show the page link action
 * @property {boolean} [showAltTitle=false] - Show an original title instead of processed
 * @property {boolean} [useAltKey=true] - Use alt key to open the link normally
 * @property {boolean|'always'|'clear'} [setClasses=true] - Set classes on the existing link element
 * @property {import('./Link').default} [initiatorLink] - A Link instance that initiated this link
 * @property {import('./Page').default} [initiatorPage] - A Page instance that initiated this link
 * @property {InstanceType<typeof import('./view').default>} [initiatorView] - A View instance that initiated this link
 * @property {(link: import('./Link').default) => void} [onRequest] - Callback fired before the View dialog loads
 * @property {(link: import('./Link').default) => void} [onLoad] - Callback fired after the View dialog loads
 * @property {(link: import('./Link').default) => void} [onOpen] - Callback fired after the View dialog opens
 * @property {(link: import('./Link').default) => void} [onClose] - Callback fired after the View dialog closes
 */

/**
 * Link MediaWiki-specific metadata and context information
 * @typedef {Object} Link.MW
 * @property {boolean} hasLink - Whether a link is generated by MediaWiki
 * @property {boolean} hasLine - Whether a link is part of a changelist line
 * @property {HTMLElement} [line] - Parent changelist line element
 * @property {string} [title] - Page title extracted from changelist line
 * @property {boolean} [isContent] - Whether link is in user-contributed content
 * @property {boolean} [isDiffOnly] - Whether to render only for diff links
 * @property {boolean} [isRevisionOnly] - Whether to render only for revision links
 * @property {boolean} [isPrepend] - Whether to insert a panel before link
 * @property {boolean} [isAltTitle] - Whether to show alternative title
 * @property {boolean} [isContentInside] - Whether user content is inside MW context
 */

/**
 * Class representing a link.
 */
class Link {
	/**
	 * @type {typeof utilsLink}
	 */
	static utils = utilsLink;

	/**
	 * @type {Map}
	 */
	static stack = new Map();

	/**
	 * Find all diff/revision links in the provided context using the assembled link selector.
	 * @param {JQuery<HTMLElement>} [$container] - jQuery context to search within (defaults to body content)
	 * @returns {JQuery<Element>} jQuery collection of matching link elements
	 */
	static findLinks( $container ) {
		if ( typeof $container === 'undefined' ) {
			$container = utils.getBodyContentNode();
		}
		return $container.find( id.local.linkSelector );
	}

	/**
	 * Adds a link instance to the global stack for tracking and retrieval.
	 * @param {HTMLAnchorElement} node - Link DOM element
	 * @param {import('./Link').default} link - Link instance to store
	 */
	static addLink( node, link ) {
		this.stack.set( node, link.isValid ? link : false );
	}

	/**
	 * Retrieves a link instance from the stack by its DOM node.
	 * @param {HTMLAnchorElement} node - Link DOM element
	 * @returns {import('./Link').default|false|undefined} Link instance, false if invalid, or undefined if not found
	 */
	static getLink( node ) {
		return this.stack.get( node );
	}

	/**
	 * Checks if a link node has been processed and added to the stack.
	 * @param {HTMLAnchorElement} node - Link DOM element
	 * @returns {boolean} True if a link exists in stack
	 */
	static hasLink( node ) {
		return this.stack.has( node );
	}

	/**
	 * Checks if a link instance is valid.
	 * @param {import('./Link').default} link - Link instance to check
	 * @returns {boolean} True if a link instance is valid
	 */
	static checkLink( link ) {
		return link instanceof Link && link.isValid;
	}

	/**
	 * Gets an iterator of all Link instances stored in the stack.
	 * @returns {MapIterator<import('./Link').default>} Iterator of Link instances
	 */
	static getLinks() {
		return this.stack.values();
	}

	/**
	 * List of URL search param names to collect values from.
	 * @type {string[]}
	 */
	static URL_SEARCH_COMPONENTS = [ 'title', 'curid', 'oldid', 'diff', 'direction', 'page1', 'rev1', 'page2', 'rev2' ];

	/**
	 * @type {HTMLAnchorElement}
	 */
	node;

	/**
	 * @type {Link.Options}
	 */
	options = {};

	/**
	 * @type {import('./Article').default}
	 */
	article;

	/**
	 * @type {string}
	 */
	href;

	/**
	 * @type {URL}
	 */
	url;

	/**
	 * @type {Object|undefined}
	 */
	error;

	/**
	 * @type {Object|undefined}
	 */
	revision;

	/**
	 * @type {Object|undefined}
	 */
	compare;

	/**
	 * Container for rendered DOM nodes (container, inner, error, etc.).
	 * @type {Object<string, HTMLElement>}
	 */
	nodes = {};

	/**
	 * MediaWiki-specific link metadata and context information.
	 * @type {Link.MW}
	 */
	mw = {
		hasLink: false,
		hasLine: false,
	};

	/**
	 * Manual configuration from data attributes.
	 * @type {Object}
	 * @property {string} behavior - Manually specified behavior type
	 * @property {Object} options - Options from data-instantdiffs-options attribute
	 */
	manual = {
		behavior: 'basic',
		options: {},
	};

	/**
	 * Rendered action button instances (action, page, etc.).
	 * @type {Object<string, import('./Button').default>}
	 */
	actions = {};

	/**
	 * Extension-specific data and integrations.
	 * @type {Object}
	 */
	extensions = {};

	/**
	 * Whether the link is a valid diff or revision link.
	 * @type {boolean}
	 */
	isValid = false;

	/**
	 * Whether the link points to a hidden diff or revision link.
	 * @type {boolean}
	 */
	isHidden = false;

	/**
	 * Whether the link points to a foreign wiki.
	 * @type {boolean}
	 */
	isForeign = false;

	/**
	 * Whether an API request is currently in progress.
	 * @type {boolean}
	 */
	isLoading = false;

	/**
	 * Whether the link data has been loaded (successfully or with an error).
	 * @type {boolean}
	 */
	isLoaded = false;

	/**
	 * Whether the link is currently being observed by IntersectionObserver.
	 * @type {boolean}
	 */
	isObserved = false;

	/**
	 * Creates a Link instance for a diff or revision link.
	 * Processes the link, validates it, adds it to the stack, and renders UI if valid.
	 * @param {HTMLAnchorElement} node - Link DOM element
	 * @param {Link.Options} [options] - Link configuration options
	 */
	constructor( node, options ) {
		this.node = node;

		this.options = {
			behavior: 'basic',
			insertMethod: 'insertAfter',
			showLink: settings.get( 'showLink' ),
			showPageLink: settings.get( 'showPageLink' ),
			showAltTitle: false,
			useAltKey: true,
			setClasses: true,
			initiatorLink: null,
			initiatorPage: null,
			initiatorView: null,
			onRequest: () => {},
			onLoad: () => {},
			onOpen: () => {},
			onClose: () => {},
			...options,
		};

		// Check if a link was opened from the View dialog
		if ( view.isContains( this.node ) ) {
			this.options.initiatorView = view;
			this.options.initiatorPage = view.getPage();
		}

		// Validate link href, construct the Article instance,
		// then render panel actions and attach events
		this.process();
		if ( this.isValid ) {
			this.render();
		}

		// Add a link instance to the stack
		Link.addLink( this.node, this );
	}

	/**
	 * Processes the link to extract and validate diff/revision parameters.
	 * Parses URL, extracts article values, and creates an Article instance.
	 * Sets isValid and isForeign flags based on validation results.
	 * @private
	 */
	process() {
		// Get and validate link url
		this.href = this.node.href;
		if ( utils.isEmpty( this.href ) ) return;

		try {
			this.url = new URL( this.href );
		} catch {
			return;
		}

		// Exclude links that do not match site ajax domains config
		if ( !utilsLink.isAllowedDomain( this.url.hostname ) ) return;

		// Exclude links with specific action parameters
		if ( !utilsLink.isAllowedAction( this.url.searchParams.get( 'action' ) ) ) return;

		// Exclude links with specific selectors
		if ( utilsLink.isMWLink( this.node, id.config.mwLinkExclude ) ) return;

		// Get page title from the url pathname
		const urlParts = {};
		try {
			const pathname = decodeURIComponent( this.url.pathname );
			if ( id.local.articlePathRegExp.test( pathname ) ) {
				const title = pathname.slice( id.local.mwArticlePath.length );
				urlParts.pathname = new mw.Title( title ).getPrefixedDb();
			}
		} catch {}

		// Get page title from the url title parameter
		try {
			const title = mw.util.getParamValue( 'title', this.href );
			urlParts.title = new mw.Title( title ).getPrefixedDb();
		} catch {}

		// Get article values
		let articleValues = {
			hostname: this.url.hostname,
			hash: this.url.hash,
		};

		if ( id.local.specialPagesLinksFlatRegExp.test( urlParts.title ) ) {
			// Get components from splitting url title
			articleValues = { ...articleValues, ...utilsLink.getSplitSpecialUrl( urlParts.title ) };
		} else if ( id.local.specialPagesLinksFlatRegExp.test( urlParts.pathname ) ) {
			// Get components from splitting url pathname
			articleValues = { ...articleValues, ...utilsLink.getSplitSpecialUrl( urlParts.pathname ) };
		} else {
			// Get components from url search parameters
			Link.URL_SEARCH_COMPONENTS.forEach( name => {
				articleValues[ name ] = this.url.searchParams.get( name );
			} );

			// As a last resort, get the page title from url pathname
			if ( utils.isEmpty( articleValues.title ) && !utils.isEmpty( urlParts.pathname ) ) {
				articleValues.title = urlParts.pathname;
			}
		}

		// Construct the Article instance
		this.article = new Article( articleValues );
		this.isValid = this.article.isValid;
		this.isForeign = this.article.isForeign;
		this.isHidden = this.article.isHidden;
	}

	/**
	 * Renders the link UI based on its behavior type.
	 * Processes MediaWiki context, manual options, and renders appropriate UI elements.
	 * @private
	 */
	render() {
		// Check if a link generated by MediaWiki or contributed by a user,
		// and process related options.
		this.processMWOptions();

		// Process options from the data attributes.
		this.processManualOptions();

		// Post-validate options
		this.postValidateOptions();

		// Render by behavior
		switch ( this.options.behavior ) {
			// Add an event on the existing link.
			case 'event':
				this.renderEvent();
				break;

			// Render actions for the MediaWiki's link.
			case 'basic':
				this.renderBasic();
				break;

			// Render actions lazily for the user-contributed links.
			case 'request':
				this.renderRequest();
				break;
		}
	}

	/**
	 * Processes MediaWiki-specific context and updates behavior accordingly.
	 * Detects if a link is in user content, changelist lines, or has special MW attributes.
	 * @private
	 */
	processMWOptions() {
		// Check if a link contributed by a user.
		this.mw.isContent = utilsLink.isMWLink( this.node, id.config.mwLinkContent );
		if ( this.mw.isContent ) {
			this.options.behavior = 'request';
		}

		// Check if a link generated by MediaWiki interface.
		// Make this check after the check for a user-contributed link,
		// because there can be transcluded contribution lists into the content.
		this.mw.hasLink = utilsLink.isMWLink( this.node, id.config.mwLink );
		if ( this.mw.hasLink ) {
			this.options.behavior = 'basic';

			this.mw.isDiffOnly = utilsLink.isMWLink( this.node, id.config.mwLinkDiffOnly );
			this.mw.isRevisionOnly = utilsLink.isMWLink( this.node, id.config.mwLinkRevisionOnly );

			this.mw.isPrepend = utilsLink.isMWLink( this.node, id.config.mwLinkPrepend );
			if ( this.mw.isPrepend ) {
				this.options.insertMethod = 'insertBefore';
			}

			this.mw.isAltTitle = utilsLink.isMWLink( this.node, id.config.mwLinkAltTitle );
			if ( this.mw.isAltTitle ) {
				this.options.showAltTitle = true;
			}

			// Check if a link is a child of list line
			this.mw.line = utilsLink.getMWLine( this.node );
			if ( this.mw.line ) {
				this.mw.hasLine = true;
				this.mw.line.classList.add( 'instantDiffs-line' );

				// Populate the page title from the watchlist line entry for the edge cases.
				// Link minifiers often remove titles from the links.
				// @see {@link https://ru.wikipedia.org/wiki/User:Stjn/minilink.js}
				if ( utils.isEmpty( this.article.get( 'title' ) ) ) {
					this.mw.title = utilsLink.getMWLineTitle( this.mw.line );
					this.article.set( { title: this.mw.title } );
				}
			}

			// Check if a link contributed by a user is in a commit message, etc.
			this.mw.isContentInside = utilsLink.isMWLink( this.node, id.config.mwLinkContentInside );
			if ( this.mw.isContentInside ) {
				this.options.behavior = 'request';
			}
		}
	}

	/**
	 * Processes manual configuration from data attributes.
	 * Parses data-instantdiffs-options JSON and data-instantdiffs-link behavior.
	 * @private
	 */
	processManualOptions() {
		// Get options that were manually added to the "data-instantdiffs-options" attribute
		this.manual.options = this.node.dataset.instantdiffsOptions;
		if ( !utils.isEmpty( this.manual.options ) ) {
			try {
				this.manual.options = JSON.parse( this.manual.options );
				this.options = { ...this.options, ...this.manual.options };
			} catch ( error ) {
				const errorParams = {
					type: 'link',
					tag: 'link',
					message: error?.message || error,
					silent: true,
				};
				utils.notifyError( 'error-link-options', errorParams );
			}
		}

		// Check if a link was marked manually by the "data-instantdiffs-link" attribute
		this.manual.behavior = this.node.dataset.instantdiffsLink;
		if ( !utils.isEmpty( this.manual.behavior ) ) {
			this.options.behavior = this.manual.behavior;
		}
	}

	/**
	 * Post-validates and normalizes behavior options.
	 * Converts deprecated behaviors and ensures valid behavior values.
	 * @private
	 */
	postValidateOptions() {
		// Convert deprecated behaviors
		const behaviorTable = {
			link: 'event',
			default: 'request',
		};
		if ( behaviorTable[ this.options.behavior ] ) {
			this.options.behavior = behaviorTable[ this.options.behavior ];
		}
		if ( ![ 'request', 'basic', 'event', 'none' ].includes( this.options.behavior ) ) {
			this.options.behavior = 'basic';
		}

		// Check conditions for rendering a page link action
		this.options.showLink &&= this.options.behavior !== 'event';
		this.options.showPageLink &&= this.options.behavior === 'request';
		this.options.showAltTitle ||= this.options.behavior === 'event';
		if ( ![ 'always', 'clear' ].includes( this.options.setClasses ) ) {
			this.options.setClasses &&= this.options.behavior !== 'event';
		}
	}

	/******* OBSERVER *******/

	/**
	 * Starts observing the link with IntersectionObserver for lazy loading.
	 * @private
	 */
	observe() {
		if ( this.isObserved ) return;
		this.isObserved = true;
		id.local.interactionObserver.observe( this.node );
	}

	/**
	 * Stops observing the link with IntersectionObserver.
	 * @private
	 */
	unobserve() {
		if ( !this.isObserved ) return;
		this.isObserved = false;
		id.local.interactionObserver.unobserve( this.node );
	}

	/**
	 * Callback when a link enters the viewport (IntersectionObserver callback).
	 * Triggers the API request to load link data.
	 * @internal
	 */
	intersect() {
		if ( this.isLoading || this.isLoaded || !this.isObserved ) return;
		this.unobserve();
		this.request();
	}

	/******* REQUESTS *******/

	/**
	 * Renders a link with lazy loading behavior (shows spinner, observes viewport).
	 * @private
	 */
	renderRequest() {
		if ( this.isValid ) {
			this.toggleSpinner( true );
			this.observe();
		} else {
			this.toggleSpinner( false );
			this.isLoaded = true;
			this.unobserve();
		}
	}

	/**
	 * Initiates the appropriate API request based on article type.
	 * Routes to requestRevision, requestDiff, or requestCompare.
	 * @returns {JQuery.Promise|undefined} API request promise
	 * @private
	 */
	request() {
		const type = this.article.get( 'type' );
		const typeVariant = this.article.get( 'typeVariant' );

		if ( type === 'revision' ) {
			return this.requestRevision();
		}
		if ( type === 'diff' ) {
			if ( typeVariant === 'comparePages' ) {
				return this.requestCompare();
			}
			return this.requestDiff();
		}
	}

	/******* REQUEST REVISION *******/

	/**
	 * Requests revision data from the MediaWiki API.
	 * Fetches revision content, metadata, and user information.
	 * @returns {JQuery.Promise|undefined} API request promise
	 * @private
	 */
	requestRevision() {
		if ( this.isLoading ) return;

		this.isLoading = true;
		this.error = null;

		const params = {
			action: 'query',
			prop: 'revisions',
			rvprop: [ 'ids', 'timestamp', 'comment', 'content', 'user' ],
			rvslots: 'main',
			rvsection: 0,
			format: 'json',
			formatversion: 2,
			uselang: id.local.userLanguage,
		};

		if ( !utils.isEmpty( this.article.get( 'oldid' ) ) ) {
			params.revids = this.article.get( 'oldid' );
		} else if ( !utils.isEmpty( this.article.get( 'curid' ) ) ) {
			params.pageids = this.article.get( 'curid' );
		}

		return Api.get( params, this.article )
			.then( this.onRequestRevisionDone )
			.fail( this.onRequestRevisionError );
	}

	/**
	 * Error handler for revision request failures.
	 * @param {string} error - Error message
	 * @param {Object} data - API error response data
	 * @private
	 */
	onRequestRevisionError = ( error, data ) => {
		this.isLoading = false;

		// Set article values
		this.isHidden = this.article.isHidden = true;

		// Sett error object
		this.error = {
			type: 'revision',
			tag: 'link',
			code: !utils.isEmpty( this.article.get( 'curid' ) ) ? 'curid' : 'generic',
			article: this.article,
			silent: true,
		};

		if ( data?.error ) {
			this.error.code = data.error.code;
			this.error.message = data.error.info;
		} else {
			this.error.message = error;
			utils.notifyError( `error-revision-${ this.error.code }`, this.error );
		}

		this.renderView();
	};

	/**
	 * Success handler for revision request completion.
	 * Validates response data and updates article with revision information.
	 * @param {Object} data - API response data
	 * @private
	 */
	onRequestRevisionDone = ( data ) => {
		this.isLoading = false;

		// Render error if the query request is completely failed
		const query = data?.query;
		if ( !query ) {
			return this.onRequestRevisionError( undefined, data );
		}

		// Render error if a specific error code present
		const error = getQueryRevisionError( query );
		if ( error ) {
			return this.onRequestRevisionError( undefined, { error } );
		}

		// Get page and revision data
		const page = query.pages[ 0 ];
		this.revision = page.revisions[ 0 ];

		// Set article values
		this.article.set( {
			title: page.title,
			section: utils.getRevisionSection( this.revision ),
		} );
		this.isHidden = this.article.isHidden = utils.isRevisionHidden( this.revision );

		this.renderView();
	};

	/******* REQUEST DIFF *******/

	/**
	 * Requests diff comparison data from the MediaWiki API.
	 * Compares two revisions and fetches diff metadata.
	 * @returns {JQuery.Promise|undefined} API request promise
	 * @private
	 */
	requestDiff() {
		if ( this.isLoading ) return;

		this.isLoading = true;
		this.error = null;

		const params = {
			action: 'compare',
			prop: [ 'title', 'ids', 'timestamp', 'comment', 'user' ],
			fromrev: utils.isValidID( this.article.get( 'oldid' ) ) ? this.article.get( 'oldid' ) : undefined,
			fromtitle: !utils.isEmpty( this.article.get( 'title' ) ) ? this.article.get( 'title' ) : undefined,
			torev: utils.isValidID( this.article.get( 'diff' ) ) ? this.article.get( 'diff' ) : undefined,
			torelative: utils.isValidDir( this.article.get( 'diff' ) ) ? this.article.get( 'diff' ) : undefined,
			format: 'json',
			formatversion: 2,
			uselang: id.local.userLanguage,
		};
		return Api.get( params, this.article )
			.then( this.onRequestDiffDone )
			.fail( this.onRequestDiffError );
	}

	/**
	 * Error handler for diff comparison request failures.
	 * @param {string|*} error - Error message
	 * @param {Object} data - API error response data
	 * @private
	 */
	onRequestDiffError = ( error, data ) => {
		this.isLoading = false;

		// Set article values
		this.isHidden = this.article.isHidden = true;

		// Sett error object
		this.error = {
			type: 'diff',
			tag: 'link',
			article: this.article,
			silent: true,
		};

		if ( data?.error ) {
			this.error.code = data.error.code;
			this.error.message = data.error.info;
		} else {
			this.error.message = error;
			utils.notifyError( 'error-diff-generic', this.error );
		}

		this.renderView();
	};

	/**
	 * Success handler for diff comparison request completion.
	 * Validates response data and updates article with diff information.
	 * @param {Object} data - API response data
	 * @private
	 */
	onRequestDiffDone = ( data ) => {
		this.isLoading = false;

		// Render error if the compare request is completely failed
		this.compare = data?.compare;
		if ( !this.compare ) {
			return this.onRequestDiffError( null, data );
		}

		// Set article values
		this.article.set( {
			title: utils.getCompareTitle( this.compare ),
			section: utils.getCompareSection( this.compare ),
		} );
		this.isHidden = this.article.isHidden = utils.isCompareHidden( this.compare );

		this.renderView();
	};

	/******* REQUEST COMPARE *******/

	/**
	 * Requests cross-page comparison data from the MediaWiki API.
	 * Compares revisions from different pages.
	 * @returns {JQuery.Promise|undefined} API request promise
	 * @private
	 */
	requestCompare() {
		if ( this.isLoading ) return;

		this.isLoading = true;
		this.error = null;

		const values = this.article.getValues();
		const params = {
			action: 'compare',
			prop: [ 'title', 'ids', 'timestamp', 'comment', 'user' ],
			fromrev: utils.isValidID( values.rev1 ) ? values.rev1 : undefined,
			fromtitle: !utils.isEmpty( values.page1 ) ? values.page1 : undefined,
			torev: utils.isValidID( values.rev2 ) ? values.rev2 : undefined,
			totitle: !utils.isEmpty( values.page2 ) ? values.page2 : undefined,
			format: 'json',
			formatversion: 2,
			uselang: id.local.userLanguage,
		};
		return Api.get( params, this.article )
			.then( this.onRequestCompareDone )
			.fail( this.onRequestCompareError );
	}

	/**
	 * Error handler for cross-page comparison request failures.
	 * @param {string|*} error - Error message
	 * @param {Object} data - API error response data
	 * @private
	 */
	onRequestCompareError = ( error, data ) => {
		this.isLoading = false;

		// Set article values
		this.isHidden = this.article.isHidden = true;

		// Sett error object
		this.error = {
			type: 'diff',
			tag: 'link',
			article: this.article,
			silent: true,
		};

		if ( data?.error ) {
			this.error.code = data.error.code;
			this.error.message = data.error.info;
		} else {
			this.error.message = error;
			utils.notifyError( 'error-diff-generic', this.error );
		}

		this.renderView();
	};

	/**
	 * Success handler for cross-page comparison request completion.
	 * Validates response data and updates article with diff information.
	 * @param {Object} data - API response data
	 * @private
	 */
	onRequestCompareDone = ( data ) => {
		this.isLoading = false;

		// Render error if the compare request is completely failed
		this.compare = data?.compare;
		if ( !this.compare ) {
			return this.onRequestCompareError( null, data );
		}

		// Set article values
		this.article.set( {
			oldid: this.compare.fromrevid,
			diff: this.compare.torevid,
			page1: this.compare.fromtitle,
			page2: this.compare.totitle,
			title: utils.getCompareTitle( this.compare ),
			section: utils.getCompareSection( this.compare ),
		} );
		this.isHidden = this.article.isHidden = utils.isCompareHidden( this.compare );

		this.renderView();
	};

	/******* RENDER *******/

	/**
	 * Renders a link with 'event' behavior (adds click handler to the existing link).
	 * @private
	 */
	renderEvent() {
		if ( !this.isValid ) return;

		this.renderView();
	}

	/**
	 * Renders link with 'basic' behavior.
	 * @private
	 */
	renderBasic() {
		if (
			!this.isValid ||
			( this.mw.isDiffOnly && this.article.get( 'type' ) !== 'diff' ) ||
			( this.mw.isRevisionOnly && this.article.get( 'type' ) !== 'revision' )
		) {
			return;
		}

		this.renderView();
	}

	/**
	 * Renders the link's actions.
	 * Creates an action panel with diff/revision buttons,
	 * and an error indicator if available.
	 * @private
	 */
	renderView() {
		this.isLoaded = true;
		this.toggleSpinner( false );

		// Mutate existing link element
		if ( this.options.behavior === 'event' ) {
			this.renderLinkAction();
		}

		// Render actions panel
		if ( this.options.behavior !== 'event' ) {
			this.renderWrapper();

			this.renderLinkAction();
			if ( this.options.showPageLink && !this.error ) {
				this.renderPageAction();
			}

			this.embed( this.node, this.options.insertMethod );
		}

		const statusHook = this.error ? 'renderError' : 'renderSuccess';
		mw.hook( `${ id.config.prefix }.link.${ statusHook }` ).fire( this );
		mw.hook( `${ id.config.prefix }.link.renderComplete` ).fire( this );
	}

	/**
	 * Creates the wrapper container for the action panel.
	 * @private
	 */
	renderWrapper() {
		this.nodes.container = this.nodes.inner = h( 'span', { class: [ 'instantDiffs-panel', 'nowrap', 'noprint' ] } );
	}

	/**
	 * Renders an action button with the specified configuration.
	 * @param {Object} params - Button configuration parameters
	 * @returns {import('./Button').default} Created Button instance
	 */
	renderAction( params ) {
		params = {
			tag: 'a',
			label: null,
			title: null,
			href: null,
			target: utils.getTarget( this.options.initiatorView ),
			handler: null,
			classes: [ 'text' ],
			modifiers: [],
			container: this.nodes.inner,
			...params,
		};

		params.classes = [ 'item', 'instantDiffs-action', ...params.classes ];
		params.modifiers.forEach( modifier => params.classes.push( `instantDiffs-action--${ modifier }` ) );

		return new Button( params );
	}

	/**
	 * Gets the appropriate title for the link action button.
	 * @param {string} title - Base i18n message key
	 * @returns {string} Localized title text
	 * @private
	 */
	getLinkTitle( title ) {
		// Get an original title from the link
		if ( this.options.showAltTitle && !utils.isEmpty( this.node.title ) ) {
			return this.node.title;
		}

		// Indicate it about hidden revisions
		if ( this.article.isHidden ) {
			title = `${ title }-hidden`;
		}

		return utils.msg( title );
	}

	/**
	 * Renders the main action button (diff/revision link).
	 * Either creates a new button or mutates the existing link element.
	 * @private
	 */
	renderLinkAction() {
		const type = this.article.get( 'typeVariant' ) === 'comparePages' ? 'compare-pages' : this.article.get( 'type' );
		const title = this.getLinkTitle( `${ type }-title` );

		if ( !this.options.showLink ) {
			return this.mutateLinkAction( title );
		}

		const classes = [];
		if ( this.article.isHidden ) {
			classes.push( 'error', 'error-admin' );
		}

		this.actions.action = this.renderAction( {
			label: utils.getLabel( this.article.get( 'type' ) ),
			title: title,
			classes: classes,
			modifiers: [ this.article.get( 'type' ) ],
			handler: this.openDialog.bind( this ),
			ariaHaspopup: true,
		} );
	}

	/**
	 * Mutates the existing link element to add a click handler (when showLink is false).
	 * Adds CSS classes and creates a Button instance attached to the link.
	 * @param {string} title - Tooltip title for the link
	 * @private
	 */
	mutateLinkAction( title ) {
		this.node.dataset.instantdiffsLink = this.options.behavior;

		if ( this.options.setClasses ) {
			const classes = [ 'instantDiffs-link', `instantDiffs-link--${ this.article.get( 'type' ) }`, `is-${ this.options.insertMethod }` ];
			if ( this.options.setClasses !== 'clear' ) {
				classes.push( 'instantDiffs-link--styled' );
				if ( this.article.isHidden ) {
					classes.push( 'instantDiffs-link--error' );
				}
			}
			if ( this.options.setClasses === 'clear' ) {
				classes.push( 'instantDiffs-link--clear' );
			}

			this.node.classList.remove( 'external' );
			this.node.classList.add( ...classes );
		}

		this.actions.action = new Button( {
			node: this.node,
			handler: this.openDialog.bind( this ),
			ariaHaspopup: true,
			altTitle: title,
			useAltKey: this.options.useAltKey,
		} );
	}

	/**
	 * Renders the page link action button.
	 * Provides a direct link to the article page.
	 * @private
	 */
	renderPageAction() {
		this.actions.page = this.renderAction( {
			label: utils.getLabel( 'page' ),
			title: this.article.get( 'titleTextSection' ) || this.article.get( 'titleText' ),
			href: this.article.get( 'href' ),
			modifiers: [ 'page' ],
		} );
	}

	/******* DIALOG *******/

	/**
	 * Opens the View dialog to display the diff or revision.
	 * Sets up the dialog, triggers callbacks, and loads content.
	 * @returns {JQuery.Promise} Promise that resolves when dialog content loads
	 */
	openDialog() {
		const options = {
			initiatorPage: this.options.initiatorPage,
			onOpen: () => this.onDialogOpen(),
			onClose: () => this.onDialogClose(),
		};
		const isReady = view.setup( this, options );
		if ( !isReady ) return $.Deferred().resolve().promise();

		this.onDialogRequest();
		return $.when( view.load() )
			.always( () => this.onDialogLoad() );
	}

	/**
	 * Callback fired before the View dialog loads.
	 * Shows loading cursor and triggers onRequest callback.
	 * @private
	 */
	onDialogRequest() {
		this.toggleLoader( true );

		if ( utils.isFunction( this.options.onRequest ) ) {
			this.options.onRequest( this );
		}
	}

	/**
	 * Callback fired after the View dialog loads.
	 * Hides loading cursor and triggers onLoad callback.
	 * @private
	 */
	onDialogLoad() {
		this.toggleLoader( false );

		if ( utils.isFunction( this.options.onLoad ) ) {
			this.options.onLoad( this );
		}
	}

	/**
	 * Callback fired after the View dialog opens.
	 * Highlights changelist line and triggers onOpen callback.
	 * @private
	 */
	onDialogOpen() {
		if ( this.mw.hasLine && settings.get( 'highlightLine' ) ) {
			this.mw.line.classList.add( 'instantDiffs-line--highlight' );
		}

		if ( utils.isFunction( this.options.onOpen ) ) {
			this.options.onOpen( this );
		}

		if ( this.options.initiatorLink instanceof Link ) {
			this.options.initiatorLink.onDialogOpen();
		}
	}

	/**
	 * Callback fired after the View dialog closes.
	 * Removes line highlighting, marks lines as seen, and triggers onClose callback.
	 * @private
	 */
	onDialogClose() {
		// Mark link as seen
		if ( settings.get( 'markWatchedLink' ) ) {
			this.node.classList.add( 'seen' );
		}

		// Mark list line as seen
		if ( this.mw.hasLine ) {
			if ( settings.get( 'highlightLine' ) ) {
				this.mw.line.classList.remove( 'instantDiffs-line--highlight' );
			}
			if (
				settings.get( 'markWatchedLine' ) &&
				id.config.changeLists.includes( mw.config.get( 'wgCanonicalSpecialPageName' ) )
			) {
				this.mw.line.classList.remove( ...id.config.mwLine.unseen );
				this.mw.line.classList.add( ...id.config.mwLine.seen );
			}
			if (
				settings.get( 'markWatchedLine' ) &&
				id.local.mwCanonicalSpecialPageName === 'GlobalWatchlist'
			) {
				this.mw.line.classList.add( 'instantDiffs-line--seen' );
			}
		}

		if ( utils.isFunction( this.options.onClose ) ) {
			this.options.onClose( this );
		}

		if ( this.options.initiatorLink instanceof Link ) {
			this.options.initiatorLink.onDialogClose();
		}
	}

	/******* ACTIONS *******/

	/**
	 * Toggles the pending loader cursor visibility.
	 * Shows a loading cursor on the action button or link element.
	 * @param {boolean} value - True to show loader, false to hide
	 */
	toggleLoader( value ) {
		if ( this.actions.action ) {
			this.actions.action.pending( value );
		} else {
			this.node.classList.toggle( 'instantDiffs-link--pending', value );
		}
	}

	/**
	 * Toggles the spinner loader visibility.
	 * Shows a spinning animation while lazy-loading link data.
	 * @param {boolean} value - True to show spinner, false to hide
	 */
	toggleSpinner( value ) {
		const classes = utils.getPlaceholderClasses( [ 'loader', this.article.get( 'type' ) ] );

		if ( value ) {
			this.node.classList.add( ...classes );
		} else {
			this.node.classList.remove( ...classes );
		}
	}

	/**
	 * Embeds the link's action panel to the specified container.
	 * @param {Element} container - Container element
	 * @param {string} [insertMethod] - Insertion method ('insertAfter' or 'insertBefore')
	 */
	embed( container, insertMethod ) {
		utils.embed( this.nodes.container, container, insertMethod );
	}

	/**
	 * Gets the link's action panel container element.
	 * @returns {Element} Container element
	 */
	getContainer() {
		return this.nodes.container;
	}

	/**
	 * Gets the link's anchor DOM element.
	 * @returns {HTMLAnchorElement} Link element
	 */
	getNode() {
		return this.node;
	}

	/**
	 * Gets the initiator Link instance (or self if no initiator).
	 * Used for tracking link chains when opening diffs from within dialogs.
	 * @returns {import('./Link').default} Initiator Link instance
	 */
	getInitiatorLink() {
		return this.options.initiatorLink || this;
	}

	/**
	 * Gets the associated Article instance.
	 * @returns {import('./Article').default} Article instance
	 */
	getArticle() {
		return this.article;
	}

	/**
	 * Gets the MediaWiki-specific metadata object.
	 * @returns {Link.MW} MediaWiki metadata (hasLink, hasLine, line, title, etc.)
	 */
	getMW() {
		return this.mw;
	}
}

export default Link;